### ISSUE TITLE
Can Flux support multiple versions of the same service in a cluster?

### ISSUE THREAD

**Issue by dwhiteddsoft** [fluxcd/multi-tenancy#18]
What I would like to do is test multiple versions of a service in the same cluster. I can see how to do at the k8s level. What I keep getting caught up on is how would this work at the git level. I have not seen (might simply be my lack of knowledge) something as simple as getting a service from a branch. Or is this simply multiple giturl settings?

**Comment by HighwayofLife** [comment]
You would perhaps just create a folder for each service version, I'd also think about keeping them in different namespaces to avoid collisions.
